const TABLE_PREFIX = 'datahub-reporting.ssot.ssot_';
const commonDimensions = ['brand','consents','new_vs_returning','device_type','os','browser','screen_resolution_group','ad_block','channel','medium','source','referrer','campaign','page_url','pagination','document_id','gallery_origin_document_id','page_type','parent_brand','content','locked_state','country'];
const popularDimensions = new Set(['brand','device_type','page_type','document_id','page_url','channel','consents','published_date','article_title']);
const popularMetricIds = new Set(['page_views','sessions','consent_users','nonconsent_users','real_users','virtual_page_views','nonvirtual_page_views','bounces','entrances','exits','total_time_spent','video_total_time_spent','published_articles']);
const catalogs = {
  page_views:{label:'Page views',description:'Návštěvnost a uživatelé',dimensions:[...commonDimensions,'article_rubric'],metrics:[
    ['page_views','Page views','SUM(page_views)'],['sessions','Sessions','HLL_COUNT.MERGE(hll_session_ids)'],['consent_users','Consent users','HLL_COUNT.MERGE(hll_cookie_ids)'],['nonconsent_users','Non-consent users',nonConsent('hll_cookie_ids','hll_pseudo_ids')],['real_users','Real users',realUsers('hll_cookie_ids','hll_pseudo_ids')],['virtual_page_views','Virtual page views','SUM(metrics.virtual_page_view.events)'],['nonvirtual_page_views','Nonvirtual page views','SUM(metrics.nonvirtual_page_view.events)']]},
  bounces:simple('Bounces','Opuštěné vstupy','bounces'), entrances:simple('Entrances','Vstupy','entrances'), exits:simple('Exits','Odchody','exits'),
  total_time_spent:{...simple('Total time spent','Celkový čas','total_time_spent'),metrics:[['total_time_spent','Total time spent','SUM(total_time_spent)']]},
  click_events:{label:'Click events',description:'Kliknutí a unikátní uživatelé',dimensions:[...commonDimensions,'click_url','click_itm_modul','click_itm_template','click_itm_area','click_itm_brand','click_itm_position','destination_page_type','link_type'],metrics:eventMetrics('any_click','Clicks')},
  scroll_events:{label:'Scroll events',description:'Hloubka scrollování',dimensions:commonDimensions,metrics:['scroll_title','scroll_pass25','scroll_pass50','scroll_pass75','scroll_pass100'].flatMap(e=>eventMetrics(e,e.replaceAll('_',' ')))},
  social_all_events:{label:'Social events',description:'Sdílení a social akce',dimensions:commonDimensions,metrics:['disqus_click','facebook_share','whatsapp_share','email_share','telegram_share','copy_link'].flatMap(e=>eventMetrics(e,e.replaceAll('_',' '),false))},
  video_main_events:{label:'Video events',description:'Přehrání a průchod videem',dimensions:[...commonDimensions,'video_local_ID','video_player_template','video_player_position','floating','autoplay'],metrics:['video_view','initial_play','replay','replay_button_click','in_viewport','pass25','pass50','pass75','pass100','show_paywall','click_paywall','pass_paywall'].flatMap(e=>eventMetrics(e,e.replaceAll('_',' ')))},
  video_total_time_spent:{label:'Video time spent',description:'Čas sledování videa',dimensions:[...commonDimensions,'video_local_ID','video_player_template','video_player_position','floating','autoplay'],metrics:[['video_total_time_spent','Video time spent','SUM(video_total_time_spent)']]},
  articles:{label:'Articles metadata',category:'articles',description:'Statická metadata článků',table:'datahub-core-prod.edit_perf_v2.articles',isStatic:true,dimensions:['brand','document_id','published_date','article_title','article_type','rubrics','rubric_title','authors','shared_users','quiz','month'],dimensionMeta:{rubrics:{type:'JSON ARRAY → STRING',hint:'Všechny názvy rubrik oddělené |'},rubric_title:{type:'JSON ARRAY → STRING',hint:'První rubrika'},authors:{type:'JSON ARRAY → STRING',hint:'Jména autorů'},shared_users:{type:'JSON',hint:'Původní JSON'},published_date:{type:'TIMESTAMP → DATE'}},dimensionSql:{document_id:'documentId AS document_id',published_date:"DATE(firstPublishedOrderDate, 'Europe/Prague') AS published_date",article_title:'articleTitle AS article_title',article_type:'articleType AS article_type',rubrics:jsonArrayTitles('rubrics','rubrics'),rubric_title:jsonFirstTitle('rubrics','rubric_title'),authors:jsonArrayNames('sharedUsers','authors'),shared_users:'sharedUsers AS shared_users'},filterSql:{document_id:'documentId',published_date:"DATE(firstPublishedOrderDate, 'Europe/Prague')",article_title:'articleTitle',article_type:'articleType',rubrics:jsonArrayTitles('rubrics',null),rubric_title:jsonFirstTitle('rubrics',null),authors:jsonArrayNames('sharedUsers',null),shared_users:'sharedUsers'},metrics:[['published_articles','Published articles','COUNT(DISTINCT documentId)']]}
};
Object.assign(catalogs,{
  fb_posts:socialSource('Facebook posts','agg_fb_day_facebook_data_posts','insertion_date',['page_id','page_name','post_id','created_time','type','media_type','url','target_url','title','message'],[['post_reactions','Reactions · cumulative','MAX(post_reactions)'],['post_likes','Likes · cumulative','MAX(post_likes)'],['comments_count','Comments · cumulative','MAX(comments_count)'],['shares_count','Shares · cumulative','MAX(shares_count)'],['post_clicks','Post clicks · cumulative','MAX(post_clicks)'],['post_media_view','Media views · cumulative','MAX(post_media_view)'],['video_views','Video views · cumulative','MAX(IFNULL(post_video_views_organic, 0) + IFNULL(post_video_views_paid, 0))']]),
  fb_posts_incremental:socialSource('Facebook posts · incremental','agg_day_facebook_data_posts_incremental','date',['brand','page_id','post_id','publish_date','type','media_type'],[['post_reactions','Reactions · daily','SUM(post_reactions)'],['comments_count','Comments · daily','SUM(comments_count)'],['shares_count','Shares · daily','SUM(shares_count)'],['views','Views · daily','SUM(views)'],['post_media_view','Media views · daily','SUM(post_media_view)'],['published_posts','Published posts','COUNT(DISTINCT IF(DATE_TRUNC(date, MONTH) = DATE_TRUNC(publish_date, MONTH), post_id, NULL))']]),
  fb_posts_by_type:socialSource('Facebook posts by type','agg_fb_facebook_data_posts_by_type','created_time',['page_id','post_id','type','media_type'],[['published_posts','Published posts','COUNT(DISTINCT post_id)']]),
  fb_pages_day:socialSource('Facebook pages · day','agg_fb_day_facebook_data_pages','day',['page_id','page_name'],[['followers_count','Followers · end state','MAX(followers_count)'],['page_video_views','Page video views · cumulative','MAX(page_video_views)'],['page_video_view_time','Video view time','SUM(page_video_view_time)']]),
  fb_pages_month:socialSource('Facebook pages · month','agg_fb_month_facebook_data_pages','day',['page_id'],[['followers_count','Followers · end state','MAX(followers_count)'],['page_video_views','Page video views · cumulative','MAX(page_video_views)']]),
  fb_reels:socialSource('Facebook reels','agg_fb_day_facebook_data_reels','insertion_date',['page_id','page_name','reel_id','created_time','description'],[['views','Views · cumulative','MAX(views)']]),
  ig_posts:socialSource('Instagram posts','agg_fb_day_instagram_data_posts','insertion_date',['page_id','page_name','post_id','created_time','media_type','media_product_type','caption','permalink'],[['views','Views · cumulative','MAX(views)'],['video_views','Video views · cumulative','MAX(video_views)'],['likes','Likes · cumulative','MAX(likes)'],['shares','Shares · cumulative','MAX(shares)'],['reach','Reach · cumulative','MAX(reach)'],['profile_visits','Profile visits · cumulative','MAX(profile_visits)']]),
  ig_pages_product:socialSource('Instagram page product types','agg_fb_day_instagram_data_pages_media_product_type','day',['page_id','page_name','media_product_type'],[['views','Views','SUM(views)']]),
  ig_pages_month:socialSource('Instagram pages · month','agg_fb_month_instagram_data_pages','day',['page_id','page_name'],[['reach','Reach · end state','MAX(reach)'],['followers_count','Followers · end state','MAX(followers_count)']]),
  ig_month_page_post_report:socialSource('Instagram monthly page/post report','agg_report_instagram_month_page_post','year_month',['brand','page_id','page_name','post_id','media_type','media_product_type'],[['views','Views','SUM(views)'],['likes','Likes','SUM(likes)'],['shares','Shares','SUM(shares)'],['reach','Reach','SUM(reach)']]),
  fb_competitor_posts:socialSource('Facebook competitor posts','agg_fb_facebook_competitor_post_data','retrieval_timestamp',['page_id','post_id','message','permalink_url','created_time'],[['reactions','Reactions · cumulative','MAX(reactions)'],['comments','Comments · cumulative','MAX(comments)'],['shares','Shares · cumulative','MAX(shares)']]),
  fb_competitor_pages:socialSource('Facebook competitor pages','agg_fb_day_facebook_competitor_data_pages','day',['page_id','page_name','brand'],[['fan_count','Fans · end state','MAX(fan_count)']]),
  fb_monetization_posts:socialSource('Facebook monetization posts','agg_fb_facebook_monetization_posts','insertion_date',['page_name','post_id'],[['micro_amount','Revenue micro amount · cumulative','MAX(micro_amount)'],['earnings','Revenue','MAX(micro_amount) / 100000000']]),
  fb_monetization_pages:socialSource('Facebook monetization pages','agg_fb_day_facebook_monetization_pages','day',['page_name'],[['micro_amount','Revenue micro amount','SUM(micro_amount)'],['earnings','Revenue','SUM(micro_amount) / 100000000']]),
  fb_monetization_breakdown:socialSource('Facebook monetization breakdown','agg_fb_day_facebook_monetization_pages_breakdown','day',['page_name','earning_source'],[['earnings','Revenue','SUM(value)']]),
  vcc_fb_posts:socialSource('VCC Facebook posts','agg_vcc_dashboard_day_facebook_data_posts','insertion_date',['page_name','post_id','created_time','title','url','message'],[['video_views_organic','Video views organic · cumulative','MAX(post_video_views_organic)'],['video_views_paid','Video views paid · cumulative','MAX(post_video_views_paid)']]),
  vcc_fb_reels:socialSource('VCC Facebook reels','agg_vcc_dashboard_day_facebook_data_reels','insertion_date',['page_name','reel_id','created_time','description'],[['views','Views · cumulative','MAX(views)']]),
  vcc_ig_posts:socialSource('VCC Instagram posts','agg_vcc_dashboard_day_instagram_data_posts','insertion_date',['page_name','post_id','created_time','media_product_type','caption','permalink'],[['views','Views · cumulative','MAX(SAFE_CAST(views AS INT64))'],['reach','Reach · cumulative','MAX(SAFE_CAST(reach AS INT64))']]),
  fb_page_map:socialSource('Facebook page → brand map','map_facebook_page_to_brand',null,['page_id','page_name','brand','utm_campaign'],[['mapping_rows','Mapping rows','COUNT(*)']]),
  ig_page_map:socialSource('Instagram page → brand map','map_instagram_page_to_brand',null,['page_id','page_name','brand'],[['mapping_rows','Mapping rows','COUNT(*)']])
});
configureDeltas('fb_posts',['post_id'],{post_reactions:'post_reactions',post_likes:'post_likes',comments_count:'comments_count',shares_count:'shares_count',post_clicks:'post_clicks',post_media_view:'post_media_view',video_views:'IFNULL(post_video_views_organic, 0) + IFNULL(post_video_views_paid, 0)'});
configureDeltas('fb_pages_day',['page_id'],{followers_count:'followers_count',page_video_views:'page_video_views'});
configureDeltas('fb_pages_month',['page_id'],{followers_count:'followers_count',page_video_views:'page_video_views'});
configureDeltas('fb_reels',['reel_id'],{views:'views'});
configureDeltas('ig_posts',['post_id'],{views:'views',video_views:'video_views',likes:'likes',shares:'shares',reach:'reach',profile_visits:'profile_visits'});
configureDeltas('ig_pages_month',['page_id'],{reach:'reach',followers_count:'followers_count'});
configureDeltas('fb_competitor_posts',['post_id'],{reactions:'reactions',comments:'comments',shares:'shares'});
configureDeltas('fb_competitor_pages',['page_id'],{fan_count:'fan_count'});
configureDeltas('fb_monetization_posts',['post_id'],{micro_amount:'micro_amount',earnings:'micro_amount / 100000000'});
configureDeltas('vcc_fb_posts',['post_id'],{video_views_organic:'post_video_views_organic',video_views_paid:'post_video_views_paid'});
configureDeltas('vcc_fb_reels',['reel_id'],{views:'views'});
configureDeltas('vcc_ig_posts',['post_id'],{views:'SAFE_CAST(views AS INT64)',reach:'SAFE_CAST(reach AS INT64)'});
['fb_posts','fb_reels','ig_posts','fb_monetization_posts'].forEach(id=>catalogs[id].dateOffsetDays=-1);
function simple(label,description,field){return{label,description,dimensions:commonDimensions,metrics:[[field,label,`SUM(${field})`]]}}
function socialSource(label,table,dateField,dimensions,metrics){return{label,category:'social',description:dateField?'Social aggregate':'Pomocná mapovací tabulka',table:`datahub-reporting.aggregate_facebook.${table}`,dateField,noDate:!dateField,dimensions,metrics}}
function configureDeltas(source,keys,fields){const c=catalogs[source];c.deltaKeys=keys;c.deltaMetrics=fields;c.description='Denní přírůstky z kumulativních snapshotů';c.metrics=c.metrics.map(m=>fields[m[0]]?[m[0],m[1].replace(' · cumulative',' · denní delta').replace(' · end state',' · denní delta'),`SUM(${m[0]}_daily)`]:m)}
function nonConsent(cookie,pseudo,prefix=''){const p=prefix?prefix+'.':'';return `CAST(ROUND(IFNULL(SAFE_DIVIDE(HLL_COUNT.MERGE(${p}${cookie}), HLL_COUNT.MERGE(IF(consents, ${p}${pseudo}, NULL))), 1) * HLL_COUNT.MERGE(IF(NOT consents, ${p}${pseudo}, NULL))) AS INT64)`}
function realUsers(cookie,pseudo,prefix=''){const p=prefix?prefix+'.':'';return `(HLL_COUNT.MERGE(${p}${cookie}) + ${nonConsent(cookie,pseudo,prefix)})`}
function eventMetrics(event,label,withUsers=true){const p=`metrics.${event}`;const a=[[`${event}_events`,`${title(label)} events`,`SUM(${p}.events)`]];if(withUsers)a.push([`${event}_sessions`,`${title(label)} sessions`,`HLL_COUNT.MERGE(${p}.hll_session_ids)`],[`${event}_users`,`${title(label)} consent users`,`HLL_COUNT.MERGE(${p}.hll_cookie_ids)`],[`${event}_nonconsent_users`,`${title(label)} non-consent users`,nonConsent('hll_cookie_ids','hll_pseudo_ids',p)],[`${event}_real_users`,`${title(label)} real users`,realUsers('hll_cookie_ids','hll_pseudo_ids',p)]);return a}
function title(s){return s.replace(/\b\w/g,c=>c.toUpperCase())}
function jsonArrayTitles(field,alias){const sql=`ARRAY_TO_STRING(ARRAY(SELECT JSON_VALUE(item, '$.Title') FROM UNNEST(JSON_QUERY_ARRAY(${field}, '$')) AS item WHERE JSON_VALUE(item, '$.Title') IS NOT NULL), ' | ')`;return alias?`${sql} AS ${alias}`:sql}
function jsonFirstTitle(field,alias){const sql=`JSON_VALUE(JSON_EXTRACT_ARRAY(TO_JSON_STRING(${field}))[SAFE_OFFSET(0)], '$.Title')`;return alias?`${sql} AS ${alias}`:sql}
function jsonArrayNames(field,alias){const sql=`ARRAY_TO_STRING(ARRAY(SELECT DISTINCT JSON_EXTRACT_SCALAR(item, '$.Name') FROM UNNEST(IFNULL(JSON_EXTRACT_ARRAY(${field}), [])) AS item WHERE JSON_EXTRACT_SCALAR(item, '$.Name') IS NOT NULL), ', ')`;return alias?`${sql} AS ${alias}`:sql}

const state={activeCategory:'ssot',sources:new Set(),dimensions:new Set(),metrics:new Map(),filters:[]};
const $=s=>document.querySelector(s);
function init(){const d=new Date(),f=new Date(d);f.setDate(d.getDate()-7);$('#dateTo').value=d.toISOString().slice(0,10);$('#dateFrom').value=f.toISOString().slice(0,10);renderSources();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.activeCategory=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));renderSources()});['dateFrom','dateTo','grain','combine','primary'].forEach(id=>$('#'+id).addEventListener('change',generate));setupSearch('dimension');setupSearch('metric');$('#addFilter').onclick=addFilter;$('#copyButton').onclick=copySql;$('#formatButton').onclick=generate;$('#themeButton').onclick=()=>document.body.classList.toggle('dark');generate()}
function sourceCategory(s){return s.category||'ssot'}
function renderSources(){const list=Object.entries(catalogs).filter(([,s])=>sourceCategory(s)===state.activeCategory);$('#sources').innerHTML=list.map(([id,s])=>`<button class="source-card ${state.sources.has(id)?'selected':''}" data-id="${id}"><span class="check">✓</span><strong>${s.label}</strong><small>${s.description}</small></button>`).join('')+(state.activeCategory==='social'?'<div class="source-note">Metriky obsahující „impressions“ jsou vyřazené. Kumulativní snapshoty se převádějí na denní přírůstky pomocí LAG a až potom sčítají.</div>':'');document.querySelectorAll('.source-card').forEach(b=>b.onclick=()=>{const id=b.dataset.id;state.sources.has(id)?state.sources.delete(id):state.sources.add(id);for(const k of [...state.metrics.keys()])if(k.startsWith(id+':'))state.metrics.delete(k);syncDimensions();renderAll()})}
function syncDimensions(){const allowed=new Set([...state.sources].flatMap(s=>catalogs[s].dimensions));for(const d of state.dimensions)if(!allowed.has(d))state.dimensions.delete(d)}
function renderAll(){renderSources();renderDimensions();renderMetrics();renderPrimary();renderFilters();generate();$('#sourceCount').textContent=state.sources.size;$('#dimensionCount').textContent=state.dimensions.size;$('#metricCount').textContent=state.metrics.size}
function renderDimensions(){const dims=[...new Set([...state.sources].flatMap(s=>catalogs[s].dimensions))];const shown=dims.filter(d=>popularDimensions.has(d)||state.dimensions.has(d));$('#dimensions').className=dims.length?'choice-grid':'choice-grid empty-state';$('#dimensions').innerHTML=dims.length?shown.map(d=>{const meta=dimensionMetadata(d);return `<button class="choice ${state.dimensions.has(d)?'selected':''}" data-d="${d}">${d}${popularDimensions.has(d)?'<span class="popular-badge">TOP</span>':''}${meta?`<small>${meta.type}</small>`:''}</button>`}).join('')+`<div class="more-label">Dalších ${dims.length-shown.length} dimenzí najdete ve vyhledávání.</div>`:'Nejdřív vyberte zdroj.';bindDimensionButtons()}
function renderMetrics(){const html=[...state.sources].map(s=>{const isPopular=m=>sourceCategory(catalogs[s])==='social'||popularMetricIds.has(m[0])||m[0].endsWith('_events');const visible=catalogs[s].metrics.filter(m=>isPopular(m)||state.metrics.has(s+':'+m[0]));return `<div class="metric-group"><h3>${catalogs[s].label}</h3><div class="metrics-list">${visible.map(m=>{const k=s+':'+m[0];return `<button class="metric ${state.metrics.has(k)?'selected':''}" data-m="${k}">${m[1]}${isPopular(m)?'<span class="popular-badge">TOP</span>':''}<small>${m[0]}</small></button>`}).join('')}<div class="more-label">${catalogs[s].metrics.length-visible.length} dalších metrik ve vyhledávání</div></div></div>`}).join('');$('#metrics').className=html?'metric-groups':'metric-groups empty-state';$('#metrics').innerHTML=html||'Nejdřív vyberte zdroj.';bindMetricButtons()}
function bindDimensionButtons(){document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>toggleDimension(b.dataset.d))}
function bindMetricButtons(){document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>toggleMetric(b.dataset.m))}
function toggleDimension(d){state.dimensions.has(d)?state.dimensions.delete(d):state.dimensions.add(d);renderAll()}
function toggleMetric(key){const [s,id]=key.split(':');const m=catalogs[s].metrics.find(x=>x[0]===id);state.metrics.has(key)?state.metrics.delete(key):state.metrics.set(key,{source:s,id,label:m[1],expr:m[2]});renderAll()}
function setupSearch(kind){const input=$(`#${kind}Search`),box=$(`#${kind}Suggest`);input.addEventListener('input',()=>renderSuggestions(kind));input.addEventListener('focus',()=>renderSuggestions(kind));document.addEventListener('click',e=>{if(!e.target.closest('.search-box'))box.classList.remove('open')})}
function renderSuggestions(kind){const input=$(`#${kind}Search`),box=$(`#${kind}Suggest`),q=normalize(input.value);let items=[];if(kind==='dimension'){const dims=[...new Set([...state.sources].flatMap(s=>catalogs[s].dimensions))];items=dims.filter(d=>!q||normalize(d+' '+(dimensionMetadata(d)?.hint||'')).includes(q)).map(d=>{const meta=dimensionMetadata(d);return{key:d,label:d,source:meta?.type||[...state.sources].filter(s=>catalogs[s].dimensions.includes(d)).map(s=>catalogs[s].label).join(', '),selected:state.dimensions.has(d)}})}else{for(const s of state.sources)for(const m of catalogs[s].metrics)if(!q||normalize(m[0]+' '+m[1]).includes(q))items.push({key:s+':'+m[0],label:m[1],source:catalogs[s].label,selected:state.metrics.has(s+':'+m[0])})}items=items.slice(0,40);box.innerHTML=items.length?items.map(x=>`<button class="suggestion" data-search-key="${x.key}">${x.selected?'✓ ':'＋ '}${x.label}<small>${x.source}</small></button>`).join(''):'<div class="suggestion">Nic nenalezeno</div>';box.classList.toggle('open',state.sources.size>0);box.querySelectorAll('[data-search-key]').forEach(b=>b.onclick=()=>{kind==='dimension'?toggleDimension(b.dataset.searchKey):toggleMetric(b.dataset.searchKey);input.value='';box.classList.remove('open')})}
function dimensionMetadata(d){for(const s of state.sources){const meta=catalogs[s].dimensionMeta?.[d];if(meta)return meta}return null}
function normalize(s){return String(s).toLocaleLowerCase('cs').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll('_',' ')}
function renderPrimary(){const old=$('#primary').value;$('#primary').innerHTML=[...state.sources].map(s=>`<option value="${s}">${catalogs[s].label}</option>`).join('');if(state.sources.has(old))$('#primary').value=old}
function addFilter(){const available=[...new Set([...state.sources].flatMap(s=>catalogs[s].dimensions))];state.filters.push({field:available[0]||'brand',op:'=',value:''});renderFilters();generate()}
function renderFilters(){const available=[...new Set([...state.sources].flatMap(s=>catalogs[s].dimensions))];$('#filters').innerHTML=state.filters.map((f,i)=>`<div class="filter-row"><select data-fi="${i}" data-k="field">${available.map(x=>`<option ${x===f.field?'selected':''}>${x}</option>`).join('')}</select><select data-fi="${i}" data-k="op">${['=','!=','LIKE','REGEXP_CONTAINS','IN','IS NULL','IS NOT NULL'].map(x=>`<option ${x===f.op?'selected':''}>${x}</option>`).join('')}</select><input data-fi="${i}" data-k="value" value="${escapeHtml(f.value)}" placeholder="hodnota; pro IN oddělte čárkou"><button data-remove="${i}">×</button></div>`).join('');document.querySelectorAll('[data-fi]').forEach(el=>el.oninput=()=>{state.filters[+el.dataset.fi][el.dataset.k]=el.value;generate()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.filters.splice(+b.dataset.remove,1);renderFilters();generate()})}
function sourceDateSql(source){const c=catalogs[source];if(!c.dateField)return'date';const raw=`DATE(${c.dateField})`;return c.dateOffsetDays?`DATE_SUB(${raw}, INTERVAL ${Math.abs(c.dateOffsetDays)} DAY)`:raw}
function hasOutputDate(source){const c=catalogs[source];return !c.isStatic&&!c.noDate}
function dimensionExpr(d,grain,source){const custom=catalogs[source].dimensionSql?.[d];if(custom)return custom;if(d!=='date')return d;const raw=sourceDateSql(source);if(grain==='week')return `DATE_TRUNC(${raw}, WEEK(MONDAY)) AS date`;if(grain==='month')return `DATE_TRUNC(${raw}, MONTH) AS date`;return `${raw} AS date`}
function selectedDimsFor(source){return [...state.dimensions].filter(d=>catalogs[source].dimensions.includes(d))}
function sqlValue(v){return `'${String(v).replaceAll("'","''")}'`}
function whereFor(source){const c=catalogs[source],dims=c.dimensions;const rows=[];if(!c.noDate)rows.push(c.isStatic?`DATE(firstPublishedOrderDate, 'Europe/Prague') BETWEEN DATE '${$('#dateFrom').value}' AND DATE '${$('#dateTo').value}'`:`${sourceDateSql(source)} BETWEEN DATE '${$('#dateFrom').value}' AND DATE '${$('#dateTo').value}'`);for(const f of state.filters){if(!dims.includes(f.field))continue;const field=c.filterSql?.[f.field]||f.field;if(f.op==='IS NULL'||f.op==='IS NOT NULL')rows.push(`${field} ${f.op}`);else if(f.op==='REGEXP_CONTAINS')rows.push(`REGEXP_CONTAINS(${field}, r${sqlValue(f.value)})`);else if(f.op==='IN')rows.push(`${field} IN (${f.value.split(',').map(x=>sqlValue(x.trim())).join(', ')})`);else rows.push(`${field} ${f.op} ${sqlValue(f.value)}`)}return rows.length?rows:['TRUE']}
function deltaSourceSql(c,table){const fields=Object.entries(c.deltaMetrics).map(([alias,expr])=>`      IFNULL(\n        COALESCE(\n          (${expr}) - LAG(${expr}) OVER (\n            PARTITION BY ${c.deltaKeys.join(', ')} ORDER BY ${c.dateField}\n          ),\n          ${expr}\n        ),\n        0\n      ) AS ${alias}_daily`).join(',\n');return `(\n    SELECT\n      snapshot.*,\n${fields}\n    FROM (\n      SELECT *\n      FROM \`${table}\`\n      WHERE DATE(${c.dateField}) BETWEEN DATE_SUB(DATE '${$('#dateFrom').value}', INTERVAL 35 DAY) AND DATE '${$('#dateTo').value}'\n      QUALIFY ROW_NUMBER() OVER (\n        PARTITION BY ${c.deltaKeys.join(', ')}, DATE(${c.dateField})\n        ORDER BY ${c.dateField} DESC\n      ) = 1\n    ) AS snapshot\n  )`}
function generate(){const errors=[];if(!state.sources.size)errors.push('Vyberte alespoň jeden zdroj.');if(!state.metrics.size)errors.push('Vyberte alespoň jednu metriku.');if($('#dateFrom').value>$('#dateTo').value)errors.push('Datum „Od“ musí být před datem „Do“.');const selectedSources=[...state.sources].filter(s=>[...state.metrics.values()].some(m=>m.source===s));if(state.sources.size&&selectedSources.length<state.sources.size)errors.push('Každý vybraný zdroj potřebuje alespoň jednu metriku.');let sql=errors.length?'-- '+errors.join('\n-- '):buildSql(selectedSources);$('#validation').className='validation '+(errors.length?'show':'');$('#validation').textContent=errors.join(' ');$('#sqlOutput').textContent=sql;highlight();$('#lineCount').textContent=sql.split('\n').length+' řádků';updateHint(selectedSources)}
function buildSql(sources){const grain=$('#grain').value;const includeDate=grain!=='none';const ctes=sources.map(s=>{const c=catalogs[s],dims=[...(includeDate&&hasOutputDate(s)?['date']:[]),...selectedDimsFor(s)];const metrics=[...state.metrics.values()].filter(m=>m.source===s);const select=[...dims.map(d=>`    ${dimensionExpr(d,grain,s)}`),...metrics.map(m=>`    ${m.expr} AS ${m.id}`)];const table=c.table||TABLE_PREFIX+s;const from=c.isStatic?`(\n    SELECT *\n    FROM \`${table}\`\n    WHERE DATE(firstPublishedOrderDate, 'Europe/Prague') BETWEEN DATE '${$('#dateFrom').value}' AND DATE '${$('#dateTo').value}'\n    QUALIFY ROW_NUMBER() OVER (PARTITION BY brand, documentId ORDER BY firstPublishedOrderDate DESC) = 1\n  )`:c.deltaMetrics?deltaSourceSql(c,table):`\`${table}\``;return `  ${s} AS (\n  SELECT\n${select.join(',\n')}\n  FROM ${from}\n  WHERE ${whereFor(s).join('\n    AND ')}${dims.length?`\n  GROUP BY ${dims.map((_,i)=>i+1).join(', ')}`:''}\n  )`}).join(',\n\n');if(sources.length===1)return `WITH\n${ctes}\n\nSELECT *\nFROM ${sources[0]}\nORDER BY 1;`;
  const mode=$('#combine').value==='AUTO'?'LEFT JOIN':$('#combine').value;if(mode==='UNION ALL')return buildUnion(ctes,sources);const primary=sources.includes($('#primary').value)?$('#primary').value:sources[0];const rest=sources.filter(s=>s!==primary);if(mode==='CROSS JOIN')return `WITH\n${ctes}\n\nSELECT *\nFROM ${primary}\n${rest.map(s=>`CROSS JOIN ${s}`).join('\n')};`;
  const keysFor=s=>[...(includeDate&&hasOutputDate(primary)&&hasOutputDate(s)?['date']:[]),...selectedDimsFor(primary).filter(d=>selectedDimsFor(s).includes(d))];const joins=rest.map(s=>{const keys=keysFor(s);return keys.length?`${mode} ${s} USING (${keys.join(', ')})`:`CROSS JOIN ${s} -- žádný společný klíč`}).join('\n');return `WITH\n${ctes}\n\nSELECT *\nFROM ${primary}\n${joins};`}
function buildUnion(ctes,sources){const dims=[...new Set(sources.flatMap(s=>[$('#grain').value!=='none'&&hasOutputDate(s)?'date':null,...selectedDimsFor(s)]).filter(Boolean))];const mids=[...state.metrics.values()].map(m=>m.id);const selects=sources.map(s=>{const sd=new Set([...selectedDimsFor(s),...($('#grain').value!=='none'&&hasOutputDate(s)?['date']:[])]);const sm=new Set([...state.metrics.values()].filter(m=>m.source===s).map(m=>m.id));return `SELECT '${s}' AS source_table, ${dims.map(d=>sd.has(d)?d:`NULL AS ${d}`).concat(mids.map(m=>sm.has(m)?m:`NULL AS ${m}`)).join(', ')} FROM ${s}`}).join('\nUNION ALL\n');return `WITH\n${ctes}\n\n${selects};`}
function updateHint(sources){if(sources.length<2){$('#joinHint').textContent='Pro jeden zdroj není spojení potřeba.';return}const mode=$('#combine').value;$('#joinHint').textContent=mode==='UNION ALL'?'UNION ALL zarovná schéma pomocí NULL a přidá source_table.':mode==='CROSS JOIN'?'Pozor: CROSS JOIN vytváří kartézský součin agregovaných řádků.':'Join proběhne přes datum a společné vybrané dimenze. Zvolte hlavní zdroj, jehož řádky chcete zachovat.'}
function highlight(){/* textContent intentionally retained: valid copy and no HTML injection */}
async function copySql(){await navigator.clipboard.writeText($('#sqlOutput').textContent);const b=$('#copyButton'),old=b.textContent;b.textContent='Zkopírováno ✓';setTimeout(()=>b.textContent=old,1400)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init();
